version: '3'

services:

  rstudio:

    build: 
      context: .
      dockerfile: Dockerfile

    environment:
      PASSWORD: 'asdfasdf'
      ROOT: 'TRUE'

    volumes:
      - ..:/home/rstudio/work:cached