version: '3'

services:

  rstudio:

    build: 
      context: .
      dockerfile: Dockerfile

    environment:
      ROOT: 'TRUE'
      # PASSWORD: 'changeme'
      PASSWORD: "${PASSWORD}"

    volumes:
      - ..:/home/rstudio/work:cached