version: '3'

services:

  rstudio:

    build: 
      context: .
      dockerfile: Dockerfile

    environment:
      ROOT: "TRUE"
      # default password is 'test_password'
      PASSWORD: "${RSTUDIO_PASSWORD:-test_password}"

    volumes:
      - ..:/home/rstudio/work:cached